name: flight-plan-server cicd
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dexsjw/flight-plan-server:latest

  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to github runner
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Log in to Heroku using the HEROKU_API_KEY environment variable
#      - name: Login to Heroku
#        run: heroku auth:token
#        env:
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy Docker image to Heroku
        run: |
          # Refer to https://devcenter.heroku.com/articles/container-registry-and-runtime#building-and-pushing-image-s
          # for more information
          
          # Log in to Heroku container registry
          docker login --username=${{ vars.DOCKERHUB_USERNAME }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
          
          # Pull image from Docker Hub
          docker pull dexsjw/flight-plan-server:latest
          
          # Tag the Docker image
          docker tag dexsjw/flight-plan-server:latest registry.heroku.com/flight-plan-server/web
          
          # Push to Heroku's container registry
          docker push registry.heroku.com/flight-plan-server/web
          
          # Let Heroku build image from Dockerfile and push to Container Registry
          # heroku container:push web
          
          # Release the image on Heroku
          heroku container:release web --app flight-plan-server